# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
#  - board: nrfmicro_13
#    shield: lotus58_left
#  - board: nrfmicro_13
#    shield: lotus58_right
#  - board: nrfmicro_13
#    shield: KLAKPad
  - board: nrfmicro_13
    shield: Suzaku58_left
  - board: nrfmicro_13
    shield: Suzaku58_right
#  - board: nrfmicro_13
#    shield: S58L
#  - board: nrfmicro_13
#    shield: S58R
#  - board: nrfmicro_13
#    shield: three_percent_milk