file_format: "1"
id: Suzaku
name: Suzaku
type: shield
url: https://github.com/kileo123
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - Suzaku58_left
  - Suzaku58_right